# Generated by Django 5.1.15 on 2026-08-29 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dueno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, to='items.etiqueta'),
        ),
        migrations.AddField(
            model_name='itemfoto',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='items.item'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='items.categoria'),
        ),
        migrations.AddField(
            model_name='item',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.subcategoria'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategoria',
            unique_together={('categoria', 'nombre')},
        ),
    ]
