# Generated by Django 5.1.15 on 2026-08-29 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0002_initial'),
        ('trades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='traderequest',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='items_ofrecidos',
            field=models.ManyToManyField(related_name='ofrecido_en', to='items.item'),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='items_pedidos',
            field=models.ManyToManyField(related_name='pedido_en', to='items.item'),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recibidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
