# Generated by Django 5.1.15 on 2026-08-29 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='trade_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='trades.traderequest'),
        ),
    ]
